services:
  - type: web
    name: mon-laravel
    runtime: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      cp 000-default.conf /etc/apache2/sites-available/000-default.conf
      a2enmod rewrite
      php artisan config:cache
      php artisan route:cache
    startCommand: apache2ctl -D FOREGROUND