services:
  - type: web
    name: mon-laravel
    runtime: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan storage:link
      php artisan config:cache
      php artisan route:cache
    startCommand: php -S 0.0.0.0:$PORT -t public