services:
  - type: web
    name: cfptdocs
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
    startCommand: php -S 0.0.0.0:10000 -t public
    plan: free
    autoDeploy: true
